server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
   allow-bean-definition-overriding: true
   allow-circular-references: true
  cors:
   allowed-origins: http://localhost:8080,https://app.mylab.local,http://localhost:4200
   allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
   allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Credential
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      
   